from services.analyzer import analyze_film
from services.nyc_data import find_nyc_communities
from services.storyteller import generate_discovery_story
import json
import io
import sys

# Deal with weird characters occasionally generated by Gemini in standard terminal output
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def run_demo():
    title = "Dhurandhar"
    genre = "Action / Thriller / Drama"
    synopsis = "A gritty tale of power, conspiracy, and survival in the criminal underworld, testing the boundaries of loyalty and moral ambiguity."
    poster_image_path = "/Users/swatisingh/Downloads/Dhurandhar.jpg"
    trailer_url = "https://www.youtube.com/watch?v=BKOVzHcjEIo"
    
    print(f"========== 1. ANALYZING FILM & TRAILER ==========")
    dna = analyze_film(title, genre, synopsis, poster_image_path, trailer_url)
    print(json.dumps(dna, indent=2))
    
    print("\n========== 2. FINDING NYC COMMUNITIES ==========")
    orgs = find_nyc_communities(dna)
    print(json.dumps(orgs, indent=2))
    
    print("\n========== 3. GENERATING DISCOVERY STORY ==========")
    story = generate_discovery_story(title, dna, orgs)
    print("\n" + story)

if __name__ == "__main__":
    run_demo()
